global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "alertmanager:9093"

rule_files:
  - "recording.rules.yml"
  - "alerting.rules.yml"

scrape_configs:
  - job_name: "app"
    static_configs:
      - targets:
          - "app:5000"
